name: quote_details
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  component_library:
    path: ../../component_library
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  share_plus: ^12.0.1
  flutter:
    sdk: flutter
  quote_repository:
    path: ../../quote_repository
  domain_models:
    path: ../../domain_models

dev_dependencies:
  mocktail: ^1.0.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true