name: monitoring
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_dynamic_links: ^6.0.8
  firebase_analytics: ^11.3.3
  firebase_remote_config: ^5.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

