name: sign_up
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter_localizations:
    sdk: flutter
  #intl: ^0.18.1
  component_library:
    path: ../../component_library
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  user_repository:
    path: ../../user_repository
  form_fields:
    path: ../../form_fields
  domain_models:
    path: ../../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4


flutter:
  uses-material-design: true