name: quote_list
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  #intl: ^0.18.1
  component_library:
    path: ../../component_library
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  flutter:
    sdk: flutter
  domain_models:
    path: ../../domain_models
  quote_repository:
    path: ../../quote_repository
  user_repository:
    path: ../../user_repository
  monitoring:
    path: ../../monitoring
  infinite_scroll_pagination: ^5.1.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true