name: form_fields
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  formz: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

