name: profile_menu
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  component_library:
    path: ../../component_library
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #intl: ^0.18.1
  quote_repository:
    path: ../../quote_repository
  flutter_bloc: ^9.1.1
  user_repository:
    path: ../../user_repository
  domain_models:
    path: ../../domain_models
  rxdart: ^0.28.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  