name: fav_qs_api
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.1.1
  equatable: ^2.0.5
  json_annotation: ^4.8.0
  meta: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  http_mock_adapter: ^0.6.1
  mockito: ^5.4.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1

